# docker-compose.yml for Presibo Healthcare Platform
version: '3.8'

services:
  presibo-web:
    build: .
    ports:
      - "3000:3000"
    environment:
      # Production environment variables
      NODE_ENV: production
      APP_ENV: production
      PORT: 3000
      
      # Feature flags
      ENABLE_AI_SEARCH: "true"
      ENABLE_ELDER_CARE: "true"
      ENABLE_HEALTH_TIPS: "true"
      ENABLE_HTTPS: "true"
      
      # API Configuration (set these in your deployment environment)
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      ANTHROPIC_MODEL: "claude-3-sonnet-20240229"
      
      # Contact information
      SUPPORT_PHONE: "+234 703 281 0862"
      SUPPORT_EMAIL: "info@presibo.com"
      
      # Performance settings
      CACHE_DURATION: "3600"
      
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    
    # Security settings
    security_opt:
      - no-new-privileges:true
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - presibo-web
    restart: unless-stopped